### PR TITLE
Program.cs

### PR DESCRIPTION
**Pull request by endermrn**
Name for the bot

### CODE REVIEW

**Comment by lin-e** [comment]
Not needed. The bot name or title isn't used anywhere in your commit; it's literally just an unused variable.

**Comment by lin-e** [comment]
In addition; this is an example bot. It's not meant to be used like that.

**Comment by itsGhost** [comment]
kanker

**Comment by lin-e** [comment]
I swear I removed you as a collaborator.

**Comment by ducc** [comment]
wheres my collaborator

**Comment by itsGhost** [comment]
> I swear I removed you as a collaborator.

i haxed github

**Pull request closed without merging**
